language: php

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=trunk
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest

before_script:
  - composer install --prefer-source
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - if [ $CODECLIMATE_REPO_TOKEN ]; then ./vendor/bin/test-reporter; fi;

cache:
  directories:
    - vendor/

notifications:
  email: false
